config/routes.rb
Rails.application.routes.draw do
  root 'posts#index'
  resources :posts
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  require 'net/https'
  require 'uri'
  require 'json'  
  before_action :get_api,only: %i[index]

  def index
  end

  def show
    @url = "https://docker-rails-apiapp.herokuapp.com/api/v1/posts/#{params[:id]}"
    @uri = URI(@url)
    @response = Net::HTTP.get_response(@uri)
    @output = JSON.parse(@response.body)
    @index = @output["data"]
  end

  def new
    @params = {title:params[:title],content:params[:content]}
    @headers = { "Content-Type" => "application/json" }
    @uri = URI.parse('https://docker-rails-apiapp.herokuapp.com/api/v1/posts')
    @http = Net::HTTP.new(@uri.host, @uri.port)
    @http.use_ssl = @uri.scheme === "https"
    @response = @http.post(@uri.path, @params.to_json, @headers)
    @response.code# status code
    @response.body
    redirect_to root_path
  end

  def create
    
  end

  def update
    
  end

  def destroy
    
  end

  private



  def get_api
    @url = 'https://docker-rails-apiapp.herokuapp.com/api/v1/posts'
    @uri = URI(@url)
    @response = Net::HTTP.get_response(@uri)
    @output = JSON.parse(@response.body)
    @index = @output["data"]
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GetApi</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/posts/_form.html.erb
<h1>New</h1>

<form >
  <%= form_tag( new_post_path , method: :post ) do %>
    <div>Title</div>
    <input type="text" name="title" id="title">
    <div>Content</div>
    <textarea name="content" id="content" cols="30" rows="10"></textarea>
    <input type="submit">
  <% end %>
</form>

app/views/posts/index.html.erb
<h1>Posts#index</h1>
<p>Find me in app/views/posts/index.html.erb</p>

<%= link_to "new", new_post_path %>

<table>
  <tr>
    <th>ID</th><th>title</th>
  </tr>
  <% @index.each do |i| %>
    <tr>
      <td>
        <%= i["id"] %>
      </td>
      <td>
        <%= i["title"] %>
      </td>
     
      <td>
        <%= link_to "show", post_url(i["id"]) %>
      </td>
      <td>
        <%= link_to "edit", edit_post_url(i["id"]) %>
      </td>
    </tr>
    <% end %>
</table>

app/views/posts/new.html.erb
<%= render 'form' %>

<%= link_to "back", root_path %>

app/views/posts/show.html.erb
<h1>Posts#show</h1>
<p>Find me in app/views/posts/show.html.erb</p>

<h3>title</h3>
<p>
  <%= @index["title"]%>
</p>


<h3>content</h3>

<p>
  <%= @index["content"]%>
</p>




<%= link_to "back", root_path %>